parameters:
   dcsg_mailchimp_api_connector.api.class: MailchimpApiConnector\MailchimpApi
   dcsg_mailchimp_api_connector.export.class: MailchimpApiConnector\MailchimpExportApi

services:
   dcsg_mailchimp_api_connector.adapter:
        class: %dcsg_mailchimp_api_connector.adapter.class%

   dcsg_mailchimp_api_connector.api:
        class: %dcsg_mailchimp_api_connector.api.class%
        arguments:
            - @dcsg_mailchimp_api_connector.adapter
            - %dcsg_mailchimp_api_connector.apikey%

   dcsg_mailchimp_api_connector.export:
        class: %dcsg_mailchimp_api_connector.export.class%
        arguments:
            - @dcsg_mailchimp_api_connector.adapter
            - %dcsg_mailchimp_api_connector.apikey%
